config/routes.rb
Rails.application.routes.draw do
  resources :comment_comment_likes
  resources :comment_likes
  resources :comments_comments
  resources :post_comments
  resources :comments
  resources :post_likes
  resources :messages
  resources :faqs
  resources :workshops
  resources :events
  resources :ads
  resources :posts
  resources :chats
  resources :users
  root 'pages#home'
  get 'login', to: 'pages#login'
  get 'logout', to: 'pages#logout'
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/ad.rb
class Ad < ApplicationRecord
end

app/models/chat.rb
class Chat < ApplicationRecord
    belongs_to :user
end

app/models/comment_like.rb
class CommentLike < ApplicationRecord
    belongs_to :user
    belongs_to :post_comment

end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/faq.rb
class Faq < ApplicationRecord
end

app/models/message.rb
class Message < ApplicationRecord
    belongs_to :sender, class_name: 'User', foreign_key: 'sender_id'
    belongs_to :reciptient, class_name: 'User', foreign_key: 'reciptient_id'

    scope :to_user, -> (reciptient_id){ where(reciptient_id: reciptient_id)} 
    scope :from_user, -> (sender_id){ where(sender_id: sender_id)} 
end


# def self.to(reciptient_id)
#     where(reciptient_id: reciptient_id)
# end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    has_many :post_likes
    has_many :post_comments
    
    has_many :likers, through: :post_likes, source: :user
    

    def liked_by?(user)
        likers.include? user
    end
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
    belongs_to :user
    belongs_to :post
    
    has_many :comment_likes
    has_many :cc, class_name: "CommentsComment", foreign_key: "postcomment_id"

    has_many :likers, through: :comment_likes, source: :user

    def liked_by?(user)
        likers.include? user
    end
end

app/models/post_like.rb
class PostLike < ApplicationRecord
    belongs_to :user
    belongs_to :post

end

app/models/user.rb
class User < ApplicationRecord
       
    has_many :recived_messages, class_name: 'Message', foreign_key: "reciptient_id"
    has_many :sent_messages, class_name: 'Message', foreign_key: "sender_id"

    has_many :posts
    has_many :post_likes
    has_many :post_comments
    has_many :comments_comments
    has_many :chats

    def contacts
        user_ids = (sent_messages.pluck(:reciptient_id) + recived_messages.pluck(:sender_id)).uniq
        User.where(id: user_ids).order(:name)
    end

    

end

app/models/workshop.rb
class Workshop < ApplicationRecord
end

app/controllers/workshops_controller.rb
class WorkshopsController < ApplicationController
  before_action :set_workshop, only: [:show, :edit, :update, :destroy]

  # GET /workshops
  # GET /workshops.json
  def index
    @workshops = Workshop.all
  end

  # GET /workshops/1
  # GET /workshops/1.json
  def show
  end

  # GET /workshops/new
  def new
    @workshop = Workshop.new
  end

  # GET /workshops/1/edit
  def edit
  end

  # POST /workshops
  # POST /workshops.json
  def create
    @workshop = Workshop.new(workshop_params)

    respond_to do |format|
      if @workshop.save
        format.html { redirect_to @workshop, notice: 'Workshop was successfully created.' }
        format.json { render :show, status: :created, location: @workshop }
      else
        format.html { render :new }
        format.json { render json: @workshop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /workshops/1
  # PATCH/PUT /workshops/1.json
  def update
    respond_to do |format|
      if @workshop.update(workshop_params)
        format.html { redirect_to @workshop, notice: 'Workshop was successfully updated.' }
        format.json { render :show, status: :ok, location: @workshop }
      else
        format.html { render :edit }
        format.json { render json: @workshop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workshops/1
  # DELETE /workshops/1.json
  def destroy
    @workshop.destroy
    respond_to do |format|
      format.html { redirect_to workshops_url, notice: 'Workshop was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_workshop
      @workshop = Workshop.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def workshop_params
      params.require(:workshop).permit(:user_id, :content, :link, :graphic, :start_date)
    end
end

app/helpers/ads_helper.rb
module AdsHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/faqs_helper.rb
module FaqsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/workshops_helper.rb
module WorkshopsHelper
end

app/views/workshops/_form.html.slim
= form_for(@workshop, html: { class: "form-horizontal", role: "form" }) do |f|
  - if @workshop.errors.any?
    .alert.alert-danger.alert-dismissable role="alert"
      button.close type="button" data-dismiss="alert"
        span aria-hidden="true"
          | &times;
        span.sr-only
          | Close
      h4= "#{pluralize(@workshop.errors.count,"error")} prohibited this workshop from being saved:"
      ul
        - @workshop.errors.full_messages.each do |msg|
          li= msg
  .form-group
    = f.label :user_id, class: "col-sm-2 control-label"
    .col-sm-10
      = f.number_field :user_id, class: "form-control"
  .form-group
    = f.label :content, class: "col-sm-2 control-label"
    .col-sm-10
      = f.text_field :content, class: "form-control"
  .form-group
    = f.label :link, class: "col-sm-2 control-label"
    .col-sm-10
      = f.text_field :link, class: "form-control"
  .form-group
    = f.label :graphic, class: "col-sm-2 control-label"
    .col-sm-10
      = f.text_field :graphic, class: "form-control"
  .form-group
    = f.label :start_date, class: "col-sm-2 control-label"
    .col-sm-10
      = f.date_select :start_date, class: "form-control"
  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit class: "btn btn-primary"

app/views/workshops/edit.html.slim
.page-header
  = link_to workshops_path, class: 'btn btn-default' do
    span.glyphicon.glyphicon-list-alt
    |  Back 
  = link_to @workshop, class: 'btn btn-primary' do
    span.glyphicon.glyphicon-info-sign
    |  Show 
  h1
    | Editing 
    | workshop

= render 'form'

app/views/workshops/index.html.slim
.page-header
  = link_to new_workshop_path, class: 'btn btn-primary' do 
    span.glyphicon.glyphicon-plus
    |  New Workshop
  h1
    | Listing workshops

.table-responsive
  table.table.table-striped.table-bordered.table-hover
    thead
      tr
        th
          | User
        th
          | Content
        th
          | Link
        th
          | Graphic
        th
          | Start date
        th
        th
        th
    tbody
      - @workshops.each do | workshop |
        tr
          td
            = workshop.user_id
          td
            = workshop.content
          td
            = workshop.link
          td
            = workshop.graphic
          td
            = workshop.start_date
          td
            = link_to 'Show', workshop
          td
            = link_to 'Edit', edit_workshop_path(workshop) 
          td
            = link_to 'Destroy', workshop, method: :delete, data: { confirm: 'Are you sure?' } 

app/views/workshops/new.html.slim
.page-header
  = link_to workshops_path, class: 'btn btn-default' do 
    span.glyphicon.glyphicon-list-alt
    |  Back 
  h1
    | New 
    | workshop

= render 'form'

app/views/workshops/show.html.slim
.page-header
  = link_to workshops_path, class: 'btn btn-default' do 
    span.glyphicon.glyphicon-list-alt
    |  Back 
  = link_to edit_workshop_path(@workshop), class: 'btn btn-primary' do 
    span.glyphicon.glyphicon-pencil
    |  Edit 
  h1
    | Show workshop
dl.dl-horizontal
  dt
    | User:
  dd
    = @workshop.user_id
  dt
    | Content:
  dd
    = @workshop.content
  dt
    | Link:
  dd
    = @workshop.link
  dt
    | Graphic:
  dd
    = @workshop.graphic
  dt
    | Start date:
  dd
    = @workshop.start_date