config/routes.rb
Rails.application.routes.draw do
  resources :comment_comment_likes
  resources :comment_likes
  resources :comments_comments
  resources :post_comments
  resources :comments
  resources :post_likes
  resources :messages
  resources :faqs
  resources :workshops
  resources :events
  resources :ads
  resources :posts
  resources :chats
  resources :users
  root 'pages#home'
  get 'login', to: 'pages#login'
  get 'logout', to: 'pages#logout'
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/ad.rb
class Ad < ApplicationRecord
end

app/models/chat.rb
class Chat < ApplicationRecord
    belongs_to :user
end

app/models/comment_like.rb
class CommentLike < ApplicationRecord
    belongs_to :user
    belongs_to :post_comment

end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/faq.rb
class Faq < ApplicationRecord
end

app/models/message.rb
class Message < ApplicationRecord
    belongs_to :sender, class_name: 'User', foreign_key: 'sender_id'
    belongs_to :reciptient, class_name: 'User', foreign_key: 'reciptient_id'

    scope :to_user, -> (reciptient_id){ where(reciptient_id: reciptient_id)} 
    scope :from_user, -> (sender_id){ where(sender_id: sender_id)} 
end


# def self.to(reciptient_id)
#     where(reciptient_id: reciptient_id)
# end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    has_many :post_likes
    has_many :post_comments
    
    has_many :likers, through: :post_likes, source: :user
    

    def liked_by?(user)
        likers.include? user
    end
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
    belongs_to :user
    belongs_to :post
    
    has_many :comment_likes
    has_many :cc, class_name: "CommentsComment", foreign_key: "postcomment_id"

    has_many :likers, through: :comment_likes, source: :user

    def liked_by?(user)
        likers.include? user
    end
end

app/models/post_like.rb
class PostLike < ApplicationRecord
    belongs_to :user
    belongs_to :post

end

app/models/user.rb
class User < ApplicationRecord
       
    has_many :recived_messages, class_name: 'Message', foreign_key: "reciptient_id"
    has_many :sent_messages, class_name: 'Message', foreign_key: "sender_id"

    has_many :posts
    has_many :post_likes
    has_many :post_comments
    has_many :comments_comments
    has_many :chats

    def contacts
        user_ids = (sent_messages.pluck(:reciptient_id) + recived_messages.pluck(:sender_id)).uniq
        User.where(id: user_ids).order(:name)
    end

    

end

app/models/workshop.rb
class Workshop < ApplicationRecord
end

app/controllers/faqs_controller.rb
class FaqsController < ApplicationController
  before_action :set_faq, only: [:show, :edit, :update, :destroy]

  # GET /faqs
  # GET /faqs.json
  def index
    @faqs = Faq.all
  end

  # GET /faqs/1
  # GET /faqs/1.json
  def show
  end

  # GET /faqs/new
  def new
    @faq = Faq.new
  end

  # GET /faqs/1/edit
  def edit
  end

  # POST /faqs
  # POST /faqs.json
  def create
    @faq = Faq.new(faq_params)

    respond_to do |format|
      if @faq.save
        format.html { redirect_to @faq, notice: 'Faq was successfully created.' }
        format.json { render :show, status: :created, location: @faq }
      else
        format.html { render :new }
        format.json { render json: @faq.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /faqs/1
  # PATCH/PUT /faqs/1.json
  def update
    respond_to do |format|
      if @faq.update(faq_params)
        format.html { redirect_to @faq, notice: 'Faq was successfully updated.' }
        format.json { render :show, status: :ok, location: @faq }
      else
        format.html { render :edit }
        format.json { render json: @faq.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /faqs/1
  # DELETE /faqs/1.json
  def destroy
    @faq.destroy
    respond_to do |format|
      format.html { redirect_to faqs_url, notice: 'Faq was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_faq
      @faq = Faq.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def faq_params
      params.require(:faq).permit(:question, :answear)
    end
end

app/helpers/ads_helper.rb
module AdsHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/faqs_helper.rb
module FaqsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/faqs/_form.html.slim
= form_for(@faq, html: { class: "form-horizontal", role: "form" }) do |f|
  - if @faq.errors.any?
    .alert.alert-danger.alert-dismissable role="alert"
      button.close type="button" data-dismiss="alert"
        span aria-hidden="true"
          | &times;
        span.sr-only
          | Close
      h4= "#{pluralize(@faq.errors.count,"error")} prohibited this faq from being saved:"
      ul
        - @faq.errors.full_messages.each do |msg|
          li= msg
  .form-group
    = f.label :question, class: "col-sm-2 control-label"
    .col-sm-10
      = f.text_field :question, class: "form-control"
  .form-group
    = f.label :answear, class: "col-sm-2 control-label"
    .col-sm-10
      = f.text_area :answear, class: "form-control"
  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit class: "btn btn-primary"

app/views/faqs/edit.html.slim
.page-header
  = link_to faqs_path, class: 'btn btn-default' do
    span.glyphicon.glyphicon-list-alt
    |  Back 
  = link_to @faq, class: 'btn btn-primary' do
    span.glyphicon.glyphicon-info-sign
    |  Show 
  h1
    | Editing 
    | faq

= render 'form'

app/views/faqs/index.html.slim
.page-header
  = link_to new_faq_path, class: 'btn btn-primary' do 
    span.glyphicon.glyphicon-plus
    |  New Faq
  h1
    | Listing faqs

.table-responsive
  table.table.table-striped.table-bordered.table-hover
    thead
      tr
        th
          | Question
        th
          | Answear
        th
        th
        th
    tbody
      - @faqs.each do | faq |
        tr
          td
            = faq.question
          td
            = faq.answear
          td
            = link_to 'Show', faq
          td
            = link_to 'Edit', edit_faq_path(faq) 
          td
            = link_to 'Destroy', faq, method: :delete, data: { confirm: 'Are you sure?' } 

app/views/faqs/new.html.slim
.page-header
  = link_to faqs_path, class: 'btn btn-default' do 
    span.glyphicon.glyphicon-list-alt
    |  Back 
  h1
    | New 
    | faq

= render 'form'

app/views/faqs/show.html.slim
.page-header
  = link_to faqs_path, class: 'btn btn-default' do 
    span.glyphicon.glyphicon-list-alt
    |  Back 
  = link_to edit_faq_path(@faq), class: 'btn btn-primary' do 
    span.glyphicon.glyphicon-pencil
    |  Edit 
  h1
    | Show faq
dl.dl-horizontal
  dt
    | Question:
  dd
    = @faq.question
  dt
    | Answear:
  dd
    = @faq.answear