config/routes.rb
Rails.application.routes.draw do
  resources :comment_comment_likes
  resources :comment_likes
  resources :comments_comments
  resources :post_comments
  resources :comments
  resources :post_likes
  resources :messages
  resources :faqs
  resources :workshops
  resources :events
  resources :ads
  resources :posts
  resources :chats
  resources :users
  root 'pages#home'
  get 'login', to: 'pages#login'
  get 'logout', to: 'pages#logout'
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/ad.rb
class Ad < ApplicationRecord
end

app/models/chat.rb
class Chat < ApplicationRecord
    belongs_to :user
end

app/models/comment_like.rb
class CommentLike < ApplicationRecord
    belongs_to :user
    belongs_to :post_comment

end

app/models/comments_comment.rb
class CommentsComment < ApplicationRecord
    belongs_to :user
    belongs_to :post_comment, class_name: 'PostComment', foreign_key: 'postcomment_id'
end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/faq.rb
class Faq < ApplicationRecord
end

app/models/message.rb
class Message < ApplicationRecord
    belongs_to :sender, class_name: 'User', foreign_key: 'sender_id'
    belongs_to :reciptient, class_name: 'User', foreign_key: 'reciptient_id'

    scope :to_user, -> (reciptient_id){ where(reciptient_id: reciptient_id)} 
    scope :from_user, -> (sender_id){ where(sender_id: sender_id)} 
end


# def self.to(reciptient_id)
#     where(reciptient_id: reciptient_id)
# end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    has_many :post_likes
    has_many :post_comments
    
    has_many :likers, through: :post_likes, source: :user
    

    def liked_by?(user)
        likers.include? user
    end
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
    belongs_to :user
    belongs_to :post
    
    has_many :comment_likes
    has_many :cc, class_name: "CommentsComment", foreign_key: "postcomment_id"

    has_many :likers, through: :comment_likes, source: :user

    def liked_by?(user)
        likers.include? user
    end
end

app/models/post_like.rb
class PostLike < ApplicationRecord
    belongs_to :user
    belongs_to :post

end

app/models/user.rb
class User < ApplicationRecord
       
    has_many :recived_messages, class_name: 'Message', foreign_key: "reciptient_id"
    has_many :sent_messages, class_name: 'Message', foreign_key: "sender_id"

    has_many :posts
    has_many :post_likes
    has_many :post_comments
    has_many :comments_comments
    has_many :chats

    def contacts
        user_ids = (sent_messages.pluck(:reciptient_id) + recived_messages.pluck(:sender_id)).uniq
        User.where(id: user_ids).order(:name)
    end

    

end

app/models/workshop.rb
class Workshop < ApplicationRecord
end

app/controllers/comments_comments_controller.rb
class CommentsCommentsController < ApplicationController
  before_action :set_comments_comment, only: [:show, :edit, :update, :destroy]

  def index
    @comments_comments = CommentsComment.all
  end

  def show
  end

  def new
    @comments_comment = CommentsComment.new
    @comments_comment.postcomment_id = params[:postcomment_id]
  end

  def edit
  end

  def create
    @comments_comment = CommentsComment.new(comments_comment_params)
    @comments_comment.user_id = current_user.id

    if @comments_comment.save
      redirect_to @comments_comment.post_comment.post
    else
      render :new 
    end
  end

  def update
    if @comments_comment.update(comments_comment_params)
      redirect_to @comments_comment, notice: 'Comments comment was successfully updated.' 
    else
      render :edit 
    end
  end

  def destroy
    @comments_comment.destroy
    redirect_to comments_comments_url, notice: 'Comments comment was successfully destroyed.' 
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comments_comment
      @comments_comment = CommentsComment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comments_comment_params
      params.require(:comments_comment).permit(:content, :user_id, :postcomment_id)
    end
end

app/helpers/ads_helper.rb
module AdsHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/comments_comments_helper.rb
module CommentsCommentsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/faqs_helper.rb
module FaqsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments_comments/_form.html.slim
= form_for(@comments_comment, html: { class: "form-horizontal", role: "form" }) do |f|
  .form-group
    = f.label "Tekst", class: "col-sm-2 control-label"
    .col-sm-10
      = f.text_area :content, class: "form-control"
      = f.hidden_field :postcomment_id, value: @comments_comment.postcomment_id
  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit "Dodaj",class: "btn btn-primary"

app/views/comments_comments/edit.html.slim
.page-header
  = link_to comments_comments_path, class: 'btn btn-default' do
    span.glyphicon.glyphicon-list-alt
    |  Back 
  = link_to @comments_comment, class: 'btn btn-primary' do
    span.glyphicon.glyphicon-info-sign
    |  Show 
  h1
    | Editing 
    | comments_comment

= render 'form'

app/views/comments_comments/index.html.slim
.page-header
  = link_to new_comments_comment_path, class: 'btn btn-primary' do 
    span.glyphicon.glyphicon-plus
    |  New Comments comment
  h1
    | Listing comments_comments

.table-responsive
  table.table.table-striped.table-bordered.table-hover
    thead
      tr
        th
          | Content
        th
          | User
        th
          | Postcomment
        th
        th
        th
    tbody
      - @comments_comments.each do | comments_comment |
        tr
          td
            = comments_comment.content
          td
            = comments_comment.user_id
          td
            = comments_comment.postcomment_id
          td
            = link_to 'Show', comments_comment
          td
            = link_to 'Edit', edit_comments_comment_path(comments_comment) 
          td
            = link_to 'Destroy', comments_comment, method: :delete, data: { confirm: 'Are you sure?' } 

app/views/comments_comments/new.html.slim
.page-header
  = link_to comments_comments_path, class: 'btn btn-default' do 
    span.glyphicon.glyphicon-list-alt
    |  Powrót 
  h1
    | Odpowiedź na komentarz: 
  h4.ml-3
    | #{@comments_comment.post_comment.content}

= render 'form'

app/views/comments_comments/show.html.slim
.page-header
  = link_to comments_comments_path, class: 'btn btn-default' do 
    span.glyphicon.glyphicon-list-alt
    |  Back 
  = link_to edit_comments_comment_path(@comments_comment), class: 'btn btn-primary' do 
    span.glyphicon.glyphicon-pencil
    |  Edit 
  h1
    | Show comments_comment
dl.dl-horizontal
  dt
    | Content:
  dd
    = @comments_comment.content
  dt
    | User:
  dd
    = @comments_comment.user_id
  dt
    | Postcomment:
  dd
    = @comments_comment.postcomment_id