config/routes.rb
Rails.application.routes.draw do
  resources :comment_comment_likes
  resources :comment_likes
  resources :comments_comments
  resources :post_comments
  resources :comments
  resources :post_likes
  resources :messages
  resources :faqs
  resources :workshops
  resources :events
  resources :ads
  resources :posts
  resources :chats
  resources :users
  root 'pages#home'
  get 'login', to: 'pages#login'
  get 'logout', to: 'pages#logout'
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/ad.rb
class Ad < ApplicationRecord
end

app/models/chat.rb
class Chat < ApplicationRecord
    belongs_to :user
end

app/models/comment_like.rb
class CommentLike < ApplicationRecord
    belongs_to :user
    belongs_to :post_comment

end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/faq.rb
class Faq < ApplicationRecord
end

app/models/message.rb
class Message < ApplicationRecord
    belongs_to :sender, class_name: 'User', foreign_key: 'sender_id'
    belongs_to :reciptient, class_name: 'User', foreign_key: 'reciptient_id'

    scope :to_user, -> (reciptient_id){ where(reciptient_id: reciptient_id)} 
    scope :from_user, -> (sender_id){ where(sender_id: sender_id)} 
end


# def self.to(reciptient_id)
#     where(reciptient_id: reciptient_id)
# end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    has_many :post_likes
    has_many :post_comments
    
    has_many :likers, through: :post_likes, source: :user
    

    def liked_by?(user)
        likers.include? user
    end
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
    belongs_to :user
    belongs_to :post
    
    has_many :comment_likes
    has_many :cc, class_name: "CommentsComment", foreign_key: "postcomment_id"

    has_many :likers, through: :comment_likes, source: :user

    def liked_by?(user)
        likers.include? user
    end
end

app/models/post_like.rb
class PostLike < ApplicationRecord
    belongs_to :user
    belongs_to :post

end

app/models/user.rb
class User < ApplicationRecord
       
    has_many :recived_messages, class_name: 'Message', foreign_key: "reciptient_id"
    has_many :sent_messages, class_name: 'Message', foreign_key: "sender_id"

    has_many :posts
    has_many :post_likes
    has_many :post_comments
    has_many :comments_comments
    has_many :chats

    def contacts
        user_ids = (sent_messages.pluck(:reciptient_id) + recived_messages.pluck(:sender_id)).uniq
        User.where(id: user_ids).order(:name)
    end

    

end

app/models/workshop.rb
class Workshop < ApplicationRecord
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  
  def index
    if params[:filter_topic] 
      if params[:filter_author]
        authors = User.where("name like ?", "%#{params[:filter_author]}%").pluck(:id)
        @posts = Post.where("topic like ?", "%#{params[:filter_topic]}%").where(user_id: authors)
      else
        @posts = Post.where("topic like ?", "%#{params[:filter_topic]}%")
      end
    else
      if params[:filter_author]
        authors = User.where("name like ?", "%#{params[:filter_author]}%").pluck(:id)
        @posts = Post.where(user_id: authors)
      else
        @posts = Post.all
      end
    end
  end

  def show
    @post_comment = PostComment.new
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def create
    @post = Post.new(post_params)
    @post.important = false
    @post.user_id = current_user.id
    if @post.save
      redirect_to @post, notice: 'Post was successfully created.' 
    else
      render :new 
    end
  end

  def update
    if @post.update(post_params)
      redirect_to @post, notice: 'Post was successfully updated.' 
    else
      render :edit 
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_url, notice: 'Post was successfully destroyed.' 
  end

  private
    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:user_id, :content, :topic, :important, :filter_author, :filter_topic)
    end
end

app/helpers/ads_helper.rb
module AdsHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/faqs_helper.rb
module FaqsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/posts/_form.html.slim
= form_for(@post, html: { class: "form-horizontal", role: "form" }) do |f|
  - if @post.errors.any?
    .alert.alert-danger.alert-dismissable role="alert"
      button.close type="button" data-dismiss="alert"
        span aria-hidden="true"
          | &times;
        span.sr-only
          | Close
      h4= "#{pluralize(@post.errors.count,"error")} prohibited this post from being saved:"
      ul
        - @post.errors.full_messages.each do |msg|
          li= msg
      = f.hidden_field :user_id, value: current_user.id
  .form-group
    = f.label "Temat:", class: "col-sm-2 control-label"
    .col-sm-10
      = f.text_area :topic, class: "form-control"
  .form-group
    = f.label "Treść:", class: "col-sm-2 control-label"
    .col-sm-10
      = f.text_area :content, class: "form-control"
  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit "OK!", class: "btn btn-primary"

app/views/posts/edit.html.slim
.page-header
  h1
    | Edytowanie

= render 'form'

app/views/posts/index.html.slim
.container
  .page-header
    = link_to new_post_path, class: 'btn btn-primary nav-button shadowed' do 
      span.glyphicon.glyphicon-plus
      |  Nowy post
    h1
      | Lista postów
    = form_tag({:controller => "posts", :action => "index"}, method: :get) do
      .d-inline-block.my-auto
        = label_tag :filter_author, 'Autor:', class: ""
      .d-inline-block.F-50.my-auto
        = text_field_tag :filter_author, "", class: "form-control filter"
      .d-inline-block.my-auto
        = label_tag :filter_topic, 'Temat:', class: ""
      .d-inline-block.F-50.my-auto
        = text_field_tag :filter_topic, "", class: "form-control filter"
      .d-inline-block.my-auto
        = submit_tag 'Filtr', class: "btn btn-primary shadowed"



  - @posts.reverse_each do | post |
    - if post.user
      = link_to post do
        .post-box
          .post-head
            .post-header1
              .d-inline-block
                p
                  .nmnp.text-body.d-inline-block.margin-correction
                    | Autor: 
                  .nmnp.text-primary.d-inline-block
                    strong #{post.user.name}
                p.post-date
                  | Data dodania: #{Date.today.to_date} 
              .d-inline-block
                p
                  .nmnp.text-body.d-inline-block
                    | Temat: 
                  .nmnp.text-primary.d-inline-block
                    strong #{post.topic}
          .w3
          .bordered-bottom
            .post-content
              = post.content.truncate_words(40)+" #{'(...)' if post.content.scan(/\w+/).size > 40 }"
        
          

app/views/posts/new.html.slim
.page-header
  h1
    | Nowy post 

= render 'form'

app/views/posts/show.html.slim
.post-head
  .d-inline-block  
    p
      .nmnp.text-body.d-inline-block.margin-correction
        | Autor: 
      .nmnp.text-primary.d-inline-block
        strong #{@post.user.name}
    p
      .nmnp.text-body.d-inline-block
        | Temat: 
      .nmnp.text-primary.d-inline-block
        strong #{@post.topic}
  .d-inline-block.p-4
    = link_to "<i class='far fa-list-alt'></i>".html_safe, posts_path, class: 'post-button-sm'
    - if @post.user_id == current_user.id
      = link_to "<i class='far fa-edit'></i>".html_safe, edit_post_path(@post), class: 'post-button-sm'
      = link_to "<i class='far fa-trash-alt'></i>".html_safe, @post, method: :delete, data: { confirm: 'Are you sure?' }, class: 'post-button-sm' 
    - if @post.liked_by?(current_user)
      - postlike = PostLike.find_by(user_id: current_user.id, post_id: @post.id)
      = link_to "<i class='far fa-thumbs-up' style='color:green;'> #{@post.post_likes.count}</i>".html_safe, post_like_path(postlike_id: postlike.id,
       post_id: @post.id), :method => :delete, class: "post-button-sm", style: "width: auto;"
    - else
      = link_to "<i class='far fa-thumbs-up' style='color:gray;'> #{@post.post_likes.count}</i>".html_safe, post_likes_path(post_id: @post.id),
       :method => :post, class: "post-button-sm", style: "width: auto;"
.bordered-bottom.text-primary
  = simple_format(@post.content)
  br/
  br/
  = form_for @post_comment do |f|
    .w1
      = f.text_field :content, class: "form-control my-input", placeholder: "Nowy komentarz" 
      = f.hidden_field :parent_id_id, value: nil
      = f.hidden_field :user_id, value: current_user.id
      = f.hidden_field :post_id, value: @post.id
    .w2
      = f.submit "+", class: "button-addon1 btn btn-primary"
    .w3
  .bordered-bottom
    - @post.post_comments.each do |comment|
        p
          .nmnp.text-primary.d-inline-block
            | ~ 
          .nmnp.text-body.d-inline-block
            | #{comment.user.name}
          .nmnp.text-primary.d-inline-block
            | : #{comment.content}
          = link_to "<i class='far fa-comment'></i>".html_safe, new_comments_comment_path(postcomment_id: comment.id), class: "btn-comment"
          - if comment.liked_by?(current_user)
            - commentlike = CommentLike.find_by(user_id: current_user.id, post_comment_id: comment.id)
            = link_to "<i class='far fa-thumbs-up' style='color:green;'> #{comment.comment_likes.count}</i>".html_safe,
             comment_like_path(post_id: @post.id, user_id: current_user.id, commentlike_id: commentlike.id),
              :method => :delete, class: "comment-button", style: "width: auto;"
          - else
            = link_to "<i class='far fa-thumbs-up' style='color:gray;'> #{comment.comment_likes.count}</i>".html_safe,
             comment_likes_path(post_id: @post.id, user_id: current_user.id, comment_id: comment.id),
              :method => :post, class: "comment-button", style: "width: auto;"
          - comment.cc.each do |child|
            .ccindent
              .nmnp.text-primary.d-inline-block.comment-div
                | ~ 
              .nmnp.text-body.d-inline-block.comment-div
                | #{child.user.name}
              .nmnp.text-primary.d-inline-block.comment-div
                | : #{child.content}

          